# -*- coding: utf-8 -*-
"""p-9_DAA_ prim’s algorithm.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j7EDuSfZsuN_Vu4wJAgZEo_4dClfzRrd
"""

import heapq

def prims_algorithm(num_vertices, adj_list, start_node=0):
    # Min-heap to store edges: (weight, current_node, parent_node)
    pq = [(0, start_node, -1)]
    visited = set()
    mst = []
    total_weight = 0

    while pq and len(visited) < num_vertices:
        weight, u, parent = heapq.heappop(pq)

        if u in visited:
            continue

        visited.add(u)

        # If it's not the starting node, add the edge to the MST
        if parent != -1:
            mst.append((parent, u, weight))
            total_weight += weight

        # Explore adjacent vertices
        for v, edge_weight in adj_list[u]:
            if v not in visited:
                heapq.heappush(pq, (edge_weight, v, u))

    return mst, total_weight

# Example graph representation (Adjacency List: node -> list of (neighbor, weight))
# Graph with 4 vertices (0, 1, 2, 3)
graph = {
    0: [(1, 1), (2, 3)],
    1: [(0, 1), (2, 1), (3, 4)],
    2: [(0, 3), (1, 1), (3, 2)],
    3: [(1, 4), (2, 2)]
}

mst_edges, cost = prims_algorithm(4, graph, start_node=0)
print("Edges in MST (Parent -> Child : Weight):")
for u, v, w in mst_edges:
    print(f"{u} - {v} : {w}")
print(f"Total MST Weight: {cost}")