# -*- coding: utf-8 -*-
"""pra8 daa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iy26_Z_0ScOIRuVqn3q1fvMHzKf9tLvo
"""

from collections import deque

def bfs(graph, start_node):
    visited = set()
    queue = deque([start_node])
    visited.add(start_node)

    path = []

    while queue:
        current_node = queue.popleft()
        path.append(current_node)

        for neighbor in graph[current_node]:
            if neighbor not in visited:
                visited.add(neighbor)
                queue.append(neighbor)
    return path

# Example Usage:
graph_bfs = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': ['F'],
    'F': []
}

print("BFS Traversal:", bfs(graph_bfs, 'A'))

def dfs(graph, start_node, visited=None, path=None):
    if visited is None:
        visited = set()
    if path is None:
        path = []

    visited.add(start_node)
    path.append(start_node)

    for neighbor in graph[start_node]:
        if neighbor not in visited:
            dfs(graph, neighbor, visited, path)
    return path

# Example Usage:
graph_dfs = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': ['F'],
    'F': []
}

print("DFS Traversal:", dfs(graph_dfs, 'A'))