# -*- coding: utf-8 -*-
"""practical-4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P6SvGf5QpRPpqYOY-bvdek_eBjeFDwwG
"""

def factorial(n):
    result = 1

    for i in range(1, n + 1):
        result *= i

    return result


def main():
    try:
        num = int(input("Enter a positive integer: "))

        if num < 0:
            print("Error: Please enter a valid non-negative integer.")
            return

        if num > 20:
            print("Error: Number too large. Standard integers overflow above 20!.")
            return

        fact = factorial(num)
        print(f"The factorial of {num} is: {fact}")

    except ValueError:
        print("Error: Please enter a valid non-negative integer.")


if __name__ == "__main__":
    main()