# -*- coding: utf-8 -*-
"""PRACTICAL-8_DAA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TqGtu25u7FvwCGU03_t8a1TY_Q_rcZnB
"""

def coin_change(coins, amount):
    # DP array
    dp = [float('inf')] * (amount + 1)

    # 0 coins are needed to make amount 0
    dp[0] = 0

    # Calculate minimum coins for each amount
    for i in range(1, amount + 1):
        for coin in coins:
            if coin <= i:
                dp[i] = min(dp[i], dp[i - coin] + 1)

    # If amount cannot be made
    if dp[amount] == float('inf'):
        return -1

    return dp[amount]


# Input
coins = list(map(int, input("Enter coin denominations: ").split()))
amount = int(input("Enter the amount: "))

# Find result
result = coin_change(coins, amount)

# Output
if result == -1:
    print("The amount cannot be made using the given coins.")
else:
    print("Minimum number of coins required:", result)